version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'build'
    labels:
      - 'dependencies'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      timezone: 'Asia/Tokyo'
    commit-message:
      prefix: 'ci'
    labels:
      - 'dependencies'
      - 'github-actions'
